# Install and Configure Iptables 
# Wrote by Hoang Anh Tu
---
  - name: IPTABLES [Step 01] - Stop Firewalld
    service: 
      name: firewalld 
      state: stopped 
      enabled: no  

  - name: IPTABLES [Step 02] - Install Iptables
    yum: 
      name: "{{ item.service }}" 
      state: latest
    with_items:
      - { service: "iptables" }
      - { service: "iptables-services" }

  - name: IPTABLES [Step 03] - Add SSH Port to Firewall
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertbefore: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
      line: '{{ item }}'
      state: present
      backup: yes
    with_items:
      - '# SSH #'

  - name: IPTABLES [Step 04] - Add Web Port to Firewall
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertafter: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
      line: '{{ item }}'
      state: present
    with_items:
      - '# WEB #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT'

  - name: IPTABLES [Step 05] - Add Icinga2-ui Port to Firewall
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertbefore: '# WEB #'
      line: '{{ item }}'
      state: present
    with_items:
      - '# ICINGA2-UI #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT'
      - '# INFLUXDB #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 8086 -j ACCEPT'
      - '# GRAFANA #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 3000 -j ACCEPT'
      - '# MYSQL #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT'
    notify:
      - Restart Iptables
