{
 "title": "Device Dashboard Overview",
 "time": { "from": "2018-06-10T07:20:18.000Z", "to": "2018-06-11T08:20:18.000Z" },
 "templating": {
  "list": [
   {
    "name": "device_type",
    "label": "Device Type",
    "query": "show tag values with key = \"device_type\";"
   },
   {
    "name": "hostname",
    "label": "Device name",
    "query": "SHOW TAG VALUES from hostalive  WITH KEY = \"hostname\" where device_type =~ /$device_type/ "
   },
   {
    "name": "address",
    "label": "IP address",
    "query": "SHOW TAG VALUES from hostalive  WITH KEY = \"address\" where device_type =~ /$device_type/  and hostname =~ /$hostname/ "
   },
   {
    "name": "interface",
    "label": "Interface-check",
    "query": "SHOW TAG VALUES from /Interface-check-command/ WITH KEY = \"service\" where  hostname =~ /$hostname/ "
   }
  ]
 },
 "panels": [
  { "title": "$hostname - $address", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "STATUS",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hostalive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    }
   ]
  },
  {
   "title": "Ping4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "RTA" }
   ],
   "targets": [
    {
     "alias": "RTA",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"ping4\" WHERE (\"metric\" = 'pl' AND \"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "PL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "query": "SELECT mean(\"value\") FROM \"ping4\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'pl') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Load RE0",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.CPU.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^CPU.*.RE0.*/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "CPU Load RE1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.CPU.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^CPU.*.RE1.*/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory RE0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /Juniper Memory~/ AND \"metric\" = 'MEM_RE0') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Memory.*/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MEM_RE0" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Memory RE1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service_type\" = 'MEMORY' AND \"metric\" = 'MEM_RE1') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Memory.*/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MEM_RE1" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "TEMPERATURE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature ACX",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Temperature.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/Temp.*/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Temperature RE0",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Temperature.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/.*RE0.*/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Temperature RE1",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Temperature.*/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/.*RE1.*/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Bandwith-Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$hostname-total-InBit",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "service", "operator": "!~", "value": "/.*.ae.*./" }
     ]
    },
    {
     "alias": "$hostname-total-OutBit",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "service", "operator": "!~", "value": "/.*.ae.*./" }
     ]
    }
   ]
  }
 ]
}