{
 "title": "NMS Server",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Device name",
    "query": "SHOW TAG VALUES from hostalive WITH KEY = \"hostname\""
   },
   {
    "name": "address",
    "label": "IP address",
    "query": "SHOW TAG VALUES from hostalive  WITH KEY = \"address\" where device_type =~ /$device_type/  and hostname =~ /$hostname/ "
   }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "STATUS",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hostalive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    }
   ]
  },
  {
   "title": "Ping4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "RTA" }
   ],
   "targets": [
    {
     "alias": "RTA",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"ping4\" WHERE (\"metric\" = 'pl' AND \"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "PL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "query": "SELECT mean(\"value\") FROM \"ping4\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'pl') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total Disk space on /",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Used Disk space on /",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "disk /" }
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU Load Average",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "load",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "load1" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "TOTAL" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "USED" }
     ]
    }
   ]
  }
 ]
}