# Install and Configure Iptables 
# Wrote by Hoang Anh Tu
---
  - name: IPTABLES [Step 01] - Stop Firewalld
    service: 
      name: firewalld 
      state: stopped 
      enabled: no  

  - name: IPTABLES [Step 02] - Install Iptables
    yum: 
      name: "{{ item.service }}" 
      state: latest
    with_items:
      - { service: "iptables" }
      - { service: "iptables-services" }

  - name: IPTABLES [Step 03] - Add SSH Port to Firewall
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertbefore: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
      line: '{{ item }}'
      state: present
      backup: yes
    with_items:
      - '# SSH #'

  - name: IPTABLES [Step 04] - Add Icinga Port to Firewall
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertafter: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
      line: '{{ item }}'
      state: present
    with_items:
      - '# ICINGA2 #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 6558 -j ACCEPT'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 5665 -j ACCEPT'

  - name: IPTABLES [Step 05] - Add Web Port to Firewall (Only on UI Node)
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertbefore: '# ICINGA2 #'
      line: '{{ item }}'
      state: present
    with_items:
      - '# WEB #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT'
    when: 
      - ui_node == "on"

  - name: IPTABLES [Step 06] - Add NFS Port to Firewall (Only on UI Node)
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertbefore: '# ICINGA2 #'
      line: '{{ item }}'
      state: present
    with_items:
      - '# NFS #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 2049 -j ACCEPT'
      - '-A INPUT -p udp -m state --state NEW -m udp --dport 2049 -j ACCEPT'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT'
      - '-A INPUT -p udp -m state --state NEW -m udp --dport 111 -j ACCEPT'
    when: 
      - ui_node == "on"

  - name: IPTABLES [Step 07] - Add Icinga2-ui Port to Firewall (Only on UI Node)
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertbefore: '# ICINGA2 #'
      line: '{{ item }}'
      state: present
    with_items:
      - '# ICINGA2-UI #'
      - '-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT'
    when: 
      - ui_node == "on"
    notify:
      - Restart Iptables
